# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b5ffae213f3c508bba93b23daaceabe86c394bf1dcd73b6e05d412ea035610c094b70cc23e4e63466df2c530517a2639c278bb27dc2c9f3cf0c445260f3d9aa9

test:
  secret_key_base: f03b99b640f7ab6405ec171d959c60adeb0b83838f705e9d7a10f2b65f2cac92f38e13ab97494208cd2a6cb68a6d37d458325ff4356469ebd96744e4bad2659a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
